language: java
dist: trusty
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: jS31v0bgkUTIIswhjy4ioBt2+i6pJ+yyzkzpDo/qkLqcRnVNvUD+TNzhEPN46VrbQCT6dqIIZscMJYqh/+Z7F510EO/fSqJFil2UJbqaNoLtovj4xbiqToI/4GJFXSAA1JsVdceja1V+cX8Nb1y9MIq+Say5pHEv7hRuJ/gGN/DMdHn+qb0KWXiNzBtArs2NzK2hT/Ro65qxvH9v+ltt+L0sGqjuRHJVoI6IibqnmLqWuQXA0L9xaulmpzKAKx5E3ZAWhlMIVnpviD4yhD7yTt5slmXqKOVso4J8oFMjoiKMv7+xCKEwwFdNUpwFpBbQKw9EDfy/Z3FBI0ySLNZyl/wlpLNEJ07rWVyeEgmASR0wATwC6COD2/S8YiRIr5m43zri793qH789cfyK83kI3ee1rUBREBwiGFy1P5Y8ndy5TjZ3G3noa4Wvhf4CRtZ8i93r2+PKdN/2hbnISP+78glPhY4a5UaVFKG1JCR5PHChYs5ohT3Yn1iTr/4c3JI9Y+/pvTfZ8SoWfYvjz3lccABc1mKxUSLCsS6OcYW6eNPravZG64A5L0v4/BN1x2usKuQ0Pcx6oezpqqOMZInh9h0+PW3QMLrucQk7B0v+ADeLKu7fysgQiePQvEUmdVijcb/SLoHiBYKLl4CZLO2FYagD/0y3scezJuwrY2lyei4=
  - secure: jgv6DMTtvDpcYQxDN1fx3OkisttK3J46fXImWqS9J0xpfLHVoGjbYHOpynLd9w0Sj7vp5bSjX7hkE01FqC8WiVHRGKij10e7tb6UYdes2a4MkQwT9uwS4y3EWTk40FMXAu4EupLRUuTHN7J8JMKgKnexX3ubSdNvSU2RrIFFQ0OTmaGt4vT48n4AVNHhwz1swU4/srX6beFi1tOLR8UqTqJkpS4fENekHLeoGZ5YdTbksjuPr4EC3fcc5jJkD3ggf66W1zeuTOHsvT8DZISjzPfPRHYUoVQNJyL8OBEcr5etkp7HVvUZQ76nV38Tzzj/ZJ0c3ArATRGNtUREOAfdbJE8BWfnUMChKzTXXEKOMw4sbZeLEred8hYl663jC0Yqd93kG36/3j0hk8kOFlcnhNzWC2r5dPwKz38aB4/lLhjxMKjR0YAcSDAPBS+3keBgJ9q8NMluEXNsTp2Y9nEBWntbSJ9QhhcOzXDnr2EsNqZK2eTNUVapQ/vq8eDCuuxM6uLU2rwO80lh8thwz1RedyIuyhSck/QnVEHeosriY5QOdm99HHLI31GS8NBulvxJ8yA3n2SkoBEBR3rCKdmiEeQ0+2ynfOnC3Wq/rFb5oJaLgInhcH5S9jGg3b1zVrd8OkdatHvr13sLhhBnO6LiClFXPy/qXJEHN52FRll5mCs=
install:
- "/bin/true"
script:
- "cp -f ./.mvn/ci/settings.xml $HOME/.m2/settings.xml"
- "./.mvn/bintray-upload.sh || exit 1"
